import socket

DISCOVER_MESSAGE = "DISCOVER_SERVER_REQUEST"
DISCOVER_RESPONSE = b"DISCOVER_SERVER_RESPONSE"
HOST = ''
SERVER_IP = None

TCP_PORT = 60000
UDP_PORT = 50000

UDP_SOCKET = socket.SOCK_DGRAM
TCP_SOCKET = socket.SOCK_STREAM

ADRESS_FAMILY_SOCKET = socket.AF_INET

